[package]
name = "cmd_analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.29.0", features = ["bundled"] }
reedline = "0.19.1"
inquire = "0.6.2"
termion = "2.0.1"
